/**
 * TODO: https://www.iana.org/assignments/media-types/media-types.xhtml
 * DEFAULT: none or application/octet-stream
 */
export let MIMEType = Object.freeze({
  DEFAULT: "application/octet-stream",
  HTML: "text/html",
  CSS: "text/css",
  XML: "text/xml",
  JS: "text/javascript",
  MML: "text/mathml",
  TXT: "text/plain",
  JSON: "application/json",
  ATOM: "application/atom+xml",
  RSS: "application/rss+xml",
  JAR: "application/java-archive",
  PDF: "application/pdf",
  WASM: "application/wasm",
  PEM: "application/x-x509-ca-cert",
  CRT: "application/x-x509-ca-cert",
  DER: "application/x-x509-ca-cert",
  XHTML: "application/xhtml+xml",
  RAR: "application/x-rar-compressed",
  GIF: "image/gif",
  JPEG: "image/jpeg",
  JPG: "image/jpeg",
  PNG: "image/png",
  SVG: "image/svg",
  SVGZ: "image/svg",
  TIF: "image/tiff",
  TIFF: "image/tiff",
  WEBP: "image/webp",
  ICO: "image/x-icon",
  JNG: "image/x-jng",
  BMP: "image/bmp",
  WOFF: "font/woff",
  WOFF2: "font/woff2",
  MID: "audio/midi",
  MP3: "audio/mpeg",
  OGG: "audio/ogg",
  M4A: "audio/x-m4a",
  RA: "audio/x-realaudio",
  TS: "video/mp2t",
  MP4: "video/mp4",
  MPEG: "video/mpeg",
  MOV: "video/quicktime",
  WEBM: "video/webm",
  FLV: "video/x-flv",
  M4V: "video/x-m4v",
  MNG: "video/x-mng",
  ASX: "video/x-ms-asf",
  WMV: "video/x-ms-wmv",
  AVI: "video/x-msvideo"
});
